// Built-in AZ-400 practice questions (original content, not taken from any exam or dump site).
// Same shape as an importable question file; see sample-questions.json and README.md.
window.BUILTIN_QUESTIONS = [
  { id: 'q01', domain: 'Source control', question: 'Your team wants main to stay releasable at all times. Developers should merge small changes several times a day through pull requests. Which branching strategy fits best?', options: ['GitFlow with long-lived develop and release branches', 'Trunk-based development with short-lived feature branches', 'A fork per developer, merged at the end of each sprint', 'One long-lived branch per environment (dev, test, prod)'], answer: 1, explanation: 'Trunk-based development keeps branches short-lived and merges to main often through pull requests, so main stays deployable. GitFlow and per-environment branches create long-lived divergence and painful merges.' },
  { id: 'q02', domain: 'Source control', question: 'In Azure Repos, a pull request into main must not complete unless the CI pipeline succeeds on the merged code. Which branch policy do you configure?', options: ['Require a minimum number of reviewers', 'Check for linked work items', 'Build validation', 'Check for comment resolution'], answer: 2, explanation: 'A build validation policy queues the pipeline against the pull request merge result and blocks completion until it passes. The other policies govern reviews, traceability and discussion, not build results.' },
  { id: 'q03', domain: 'Source control', question: 'A repository holds large design and video files, and clones have become slow. The files must stay versioned but out of the normal Git object history. What should you use?', options: ['Git submodules', 'Git Large File Storage (LFS)', 'A .gitignore rule', 'Squash merges on every pull request'], answer: 1, explanation: 'Git LFS stores small pointers in the repository and keeps the file content on the LFS server, so the files stay versioned without bloating history. A .gitignore rule stops versioning them at all; submodules and squash merges do not address large binaries.' },
  { id: 'q04', domain: 'Pipelines', question: 'Complete the YAML so the pipeline runs only for commits to main that change files under src.', code: 'trigger:\n  branches:\n    include:\n    - main\n  ______:\n    include:\n    - src', options: ['pr', 'paths', 'filters', 'directories'], answer: 1, explanation: 'Path filters sit under trigger as paths with include and exclude lists, next to the branches filter. pr defines pull request triggers; filters and directories are not valid keywords.' },
  { id: 'q05', domain: 'Pipelines', question: 'A .NET pipeline spends most of its time restoring NuGet packages. Which two actions reduce the duration of each run?', options: ['Add a Cache@2 task keyed on packages.lock.json', 'Set batch: true on the CI trigger', 'Run on a self-hosted agent that keeps dependencies between runs', 'Increase the pipeline retention period'], answer: [0, 2], explanation: 'Cache@2 restores the package folder when the lock file has not changed, and a self-hosted agent keeps warm caches on disk. batch: true reduces how many runs start, not how long each one takes; retention only controls how long runs are kept.' },
  { id: 'q06', domain: 'Pipelines', question: 'You want to release a new API version to about 5% of users, watch error rates, and then widen the rollout or roll back. Which deployment pattern is this?', options: ['Blue-green', 'Canary', 'Recreate', 'Rolling update across all instances at once'], answer: 1, explanation: 'A canary release sends a small slice of traffic to the new version first and widens only while metrics stay healthy. Blue-green moves all traffic between two full environments in one step.' },
  { id: 'q07', domain: 'Pipelines', question: 'Developers want to ship unfinished features to production switched off, then turn them on for a pilot group at runtime without redeploying. What should you implement?', options: ['Deployment slot swaps in App Service', 'Feature flags with Azure App Configuration feature management', 'A separate release branch per feature', 'A pipeline variable that selects the feature at build time'], answer: 1, explanation: 'Feature flags separate deployment from release: the code ships dark, and the flag with a targeting filter turns it on for chosen users at runtime. Slots, branches and build-time variables all need a new deployment to change who sees the feature.' },
  { id: 'q08', domain: 'Pipelines', question: 'Teams need a private NuGet feed that can also serve public packages from nuget.org, keeping a saved copy of each public package they use. What should you set up?', options: ['An Azure Artifacts feed with nuget.org as an upstream source', 'A file share that every build agent maps as a local feed', 'GitHub Releases with the .nupkg files attached', 'Private packages published to nuget.org'], answer: 0, explanation: 'Azure Artifacts feeds support upstream sources: a package pulled from nuget.org through the feed is saved in the feed, so builds keep working even if the public package changes or is removed.' },
  { id: 'q09', domain: 'Pipelines', question: 'In a multi-stage YAML pipeline, a release manager must approve before anything deploys to production. What should you configure?', options: ['A required reviewers branch policy on main', 'An approval check on the Production environment, targeted by a deployment job', 'A condition of succeeded() on the production stage', 'Open access on the production service connection'], answer: 1, explanation: 'YAML pipelines use approvals and checks on protected resources. Add an approval to the Production environment and deploy with a deployment job that targets it; the run waits there until someone approves.' },
  { id: 'q10', domain: 'Pipelines', question: 'You need Azure-native, declarative infrastructure as code with concise modular syntax, a what-if preview, and no separate state file to manage. What should you use?', options: ['Bicep', 'Terraform', 'Azure CLI scripts', 'Azure Resource Graph queries'], answer: 0, explanation: 'Bicep compiles to ARM templates, supports modules and what-if, and relies on Azure itself for state. Terraform keeps a state file; CLI scripts are imperative; Resource Graph only queries existing resources.' },
  { id: 'q11', domain: 'Pipelines', question: 'A pipeline must deploy to a virtual machine that is reachable only inside a private virtual network with no public endpoint. What should run the deployment job?', options: ['A Microsoft-hosted agent with more parallel jobs', 'A Microsoft-hosted agent whose IP range is allowed on the VM', 'A self-hosted agent or Managed DevOps Pool connected to that virtual network', 'The same agent with a longer job timeout'], answer: 2, explanation: 'Microsoft-hosted agents run outside your network and cannot reach an endpoint that is private only. An agent that runs inside, or is injected into, the virtual network can.' },
  { id: 'q12', domain: 'Security', question: 'Pipelines in several projects use the same database password. Security wants to rotate it in one place without editing any pipeline. What should you do?', options: ['Add a secret variable to each pipeline', 'Link a variable group to Azure Key Vault and reference the group in each pipeline', 'Commit the password encrypted in appsettings.json', 'Upload the password as a secure file'], answer: 1, explanation: 'A variable group linked to Key Vault reads the secret at run time, so rotating it in Key Vault updates every pipeline that uses the group. Per-pipeline secrets each need editing, and secrets in the repository are a leak risk.' },
  { id: 'q13', domain: 'Security', question: 'In GitHub, you want alerts when a repository depends on open-source packages with known vulnerabilities, plus automatic pull requests that upgrade them. What should you enable?', options: ['CodeQL code scanning', 'Secret scanning push protection', 'Dependabot alerts and security updates', 'A CODEOWNERS file'], answer: 2, explanation: 'Dependabot checks your dependency graph against the GitHub Advisory Database, raises alerts and can open upgrade pull requests. CodeQL analyses your own code, secret scanning finds leaked credentials, and CODEOWNERS routes reviews.' },
  { id: 'q14', domain: 'Instrumentation', question: 'A web app sends telemetry to Application Insights. You need to find slow outbound dependency calls. Which language do you use to query the data in Log Analytics?', options: ['Kusto Query Language (KQL)', 'Transact-SQL', 'PromQL', 'Gremlin'], answer: 0, explanation: 'Application Insights and Log Analytics data is queried with KQL, for example the dependencies table filtered and summarized by duration.' },
  { id: 'q15', domain: 'Instrumentation', question: 'You must be alerted when a public website stops responding from several geographic regions, even when no users are visiting it. What should you configure?', options: ['An Application Insights availability test', 'A Log Analytics workspace retention policy', 'Azure Advisor recommendations', 'A diagnostic setting on the App Service plan'], answer: 0, explanation: 'Availability tests call the endpoint on a schedule from multiple Azure regions and can fire an alert when checks fail, independent of real user traffic.' },
  { id: 'q16', domain: 'Process', question: 'Code is in GitHub and work is tracked in Azure Boards. After connecting the repository to Azure Boards, what should developers put in commit messages to link commits to work items?', options: ['#1234', 'AB#1234', 'WI-1234', 'Fixes: 1234'], answer: 1, explanation: 'With the Azure Boards app connected, the AB#<ID> syntax links commits and pull requests to the work item. #1234 refers to a GitHub issue or pull request.' },
  { id: 'q17', domain: 'Process', question: 'Which DORA metric measures the time from a commit to that code running successfully in production?', options: ['Deployment frequency', 'Lead time for changes', 'Change failure rate', 'Failed deployment recovery time'], answer: 1, explanation: 'Lead time for changes tracks commit-to-production time. Deployment frequency counts releases, change failure rate is the share of deployments that cause failures, and recovery time is how fast service is restored.' }
];
